/**
 * Created by zhongwangsheng on 2018/4/7.
 */
export const START_QUERY_ARTICLE_LIST = 'START_QUERY_ARTICLE_LIST';
export const FINISH_QUERY_ARTICLE_LIST = 'FINISH_QUERY_ARTICLE_LIST';

export const STORE_ARTICLE_QUERY_LIST = 'STORE_ARTICLE_QUERY_LIST';
export const STORE_ARTICLE_QUERY_CONDITION = 'STORE_ARTICLE_QUERY_CONDITION';